sources:
  - name: Scroll
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/18216/omni-kingdoms/version/latest
    transforms:
      - prefix:
          value: S_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
  - name: Arbitrum
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/18216/arboktest3/version/latest
    transforms:
      - prefix:
          value: A_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
  - name: Base
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/18216/omnikingdomsbase/version/latest
    transforms:
      - prefix:
          value: B_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_