/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiamondABI } from "./DiamondABI";
export * as factories from "./factories";
export { DiamondABI__factory } from "./factories/DiamondABI__factory";
